### ISSUE TITLE
No Download, Only Blank Page on Magento 1.9

### ISSUE THREAD

**Issue by sid-ant** [staempfli/magento-pdf#1]
I did a composer install of 
> mikehaertl/phpwkhtmltopdf

and added the following line in constructor of Staempfli_Pdf_Model_Abstract
> require_once 'vendor/autoload.php';

However running a sample hello world pdf example on my custom module results in a blank page with no pdf being downloaded. 

Hello World Function

```
		public function printAction(){
			$pdf = Mage::getModel('staempfli_pdf/pdf');
			$header   = $pdf->createBlock('staempfli_pdf/pdf_header');
			$footer   = $pdf->createBlock('staempfli_pdf/pdf_footer');
			$content  = $pdf->createBlock('staempfli_pdf/pdf_content');
			$content->setTitle('My Page Title');
			$content->addContent('Hello World');
			$pdf->addPage($content->toHtml());
			$pdf->downloadPdf('filename.pdf');
			$pdf->savePdf('filename.pdf');
		}

```
I was not using Composer with my Magento 1.9 and had to install it for resolving this dependency. Composer created a 'vender/mike..' and the composer documentation instructs to include 'autoload' and hence for this reason 

> require_once 'vendor/autoload.php';

has been added.

**Comment by alejandromartincruz** [comment]
I have the same problem, did you solved it?

My code is even more simple:

       `$pdf = Mage::getModel('staempfli_pdf/pdf');
        $content = $pdf->createBlock('staempfli_pdf/pdf_content');

        $content->addContent('Hello World', 'h1');
        $pdf->addPage($content->toHtml());
        $pdf->downloadPdf('filename.pdf');`
